/*
 *  maven Programming Language
 *  Created by Elliot Chance <elliot.com>.
 */

// !!! this file will be generated by the installer script.

// the operating system, can be
// 1 - UNIX
// 2 - WINDOWS

#define MAVEN_OS 1

#define MAVEN_INI_LOCATION "../etc/maven.ini"

#define SYSTEM_RM "rm -f "
#define SYSTEM_CP "cp -f "
#define SYSTEM_MKDIR "mkdir "
